### PR TITLE
Greta/add next week schedule

### PR DESCRIPTION
**Pull request by gretahuang**
Added the next week's schedule
fixed UI for the time dropdown

### CODE REVIEW

**Comment by gretahuang** [comment]
@TheXienator

**Comment by TheXienator** [comment]
LGTM

**Comment by TheXienator** [comment]
screen shot 2017-01-30 at 2 03 26 pm
Can you make it so that only the current week's date is highlighted

**Comment by gretahuang** [comment]
@TheXienator made fixes!

**Pull request merged**
